/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'question' : IDL.Text,
  'explanationHi' : IDL.Opt(IDL.Text),
  'explanation' : IDL.Opt(IDL.Text),
  'answer' : IDL.Text,
  'optionsHi' : IDL.Opt(IDL.Vec(IDL.Text)),
  'questionHi' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const ExamCategory = IDL.Variant({
  'ssc' : IDL.Null,
  'railway' : IDL.Null,
  'bpsc' : IDL.Null,
  'upsc' : IDL.Null,
  'banking' : IDL.Null,
  'stateExams' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const CurrentAffairs = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'date' : IDL.Text,
});
export const Newspaper = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'link' : IDL.Text,
});
export const Slider = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'otp' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'profilePhotoBase64' : IDL.Opt(IDL.Text),
  'registeredAt' : Time,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'negativeMarkValue' : IDL.Float64,
  'category' : ExamCategory,
  'questions' : IDL.Vec(Question),
  'price' : IDL.Nat,
});
export const Ranker = IDL.Record({
  'studentName' : IDL.Text,
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'examCategory' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCurrentAffairs' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addNewspaper' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addRanker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addSlider' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addTest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(Question),
        IDL.Nat,
        IDL.Float64,
        ExamCategory,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCurrentAffairs' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteNewspaper' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteRanker' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteSlider' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'generateQuestions' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Question)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentAffairs' : IDL.Func([], [IDL.Vec(CurrentAffairs)], ['query']),
  'getNewspapers' : IDL.Func([], [IDL.Vec(Newspaper)], ['query']),
  'getSliders' : IDL.Func([], [IDL.Vec(Slider)], ['query']),
  'getStudentProfile' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getTestById' : IDL.Func([IDL.Nat], [Test], ['query']),
  'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getTopRankers' : IDL.Func([], [IDL.Vec(Ranker)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'studentLogout' : IDL.Func([IDL.Text], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateStudentProfilePhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTest' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(Question),
        IDL.Nat,
        IDL.Float64,
        ExamCategory,
      ],
      [],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'question' : IDL.Text,
    'explanationHi' : IDL.Opt(IDL.Text),
    'explanation' : IDL.Opt(IDL.Text),
    'answer' : IDL.Text,
    'optionsHi' : IDL.Opt(IDL.Vec(IDL.Text)),
    'questionHi' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const ExamCategory = IDL.Variant({
    'ssc' : IDL.Null,
    'railway' : IDL.Null,
    'bpsc' : IDL.Null,
    'upsc' : IDL.Null,
    'banking' : IDL.Null,
    'stateExams' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const CurrentAffairs = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'date' : IDL.Text,
  });
  const Newspaper = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'link' : IDL.Text,
  });
  const Slider = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'otp' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'profilePhotoBase64' : IDL.Opt(IDL.Text),
    'registeredAt' : Time,
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'negativeMarkValue' : IDL.Float64,
    'category' : ExamCategory,
    'questions' : IDL.Vec(Question),
    'price' : IDL.Nat,
  });
  const Ranker = IDL.Record({
    'studentName' : IDL.Text,
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'examCategory' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCurrentAffairs' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addNewspaper' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addRanker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addSlider' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addTest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(Question),
          IDL.Nat,
          IDL.Float64,
          ExamCategory,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCurrentAffairs' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteNewspaper' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteRanker' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteSlider' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'generateQuestions' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Question)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentAffairs' : IDL.Func([], [IDL.Vec(CurrentAffairs)], ['query']),
    'getNewspapers' : IDL.Func([], [IDL.Vec(Newspaper)], ['query']),
    'getSliders' : IDL.Func([], [IDL.Vec(Slider)], ['query']),
    'getStudentProfile' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getTestById' : IDL.Func([IDL.Nat], [Test], ['query']),
    'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getTopRankers' : IDL.Func([], [IDL.Vec(Ranker)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'studentLogout' : IDL.Func([IDL.Text], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateStudentProfilePhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTest' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(Question),
          IDL.Nat,
          IDL.Float64,
          ExamCategory,
        ],
        [],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };