/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Question {
  'question' : string,
  'answer' : string,
  'options' : Array<string>,
}
export interface Ranker {
  'studentName' : string,
  'rank' : bigint,
  'score' : bigint,
  'examCategory' : string,
}
export interface Test {
  'id' : bigint,
  'title' : string,
  'category' : string,
  'questions' : Array<Question>,
}
export interface _SERVICE {
  'addRanker' : ActorMethod<[string, string, string, bigint], undefined>,
  'addTest' : ActorMethod<[string, string, string, Array<Question>], undefined>,
  'deleteRanker' : ActorMethod<[string, bigint], undefined>,
  'deleteTest' : ActorMethod<[string, bigint], undefined>,
  'generateQuestions' : ActorMethod<[string, string], Array<Question>>,
  'getContactSubmissions' : ActorMethod<[string], Array<ContactSubmission>>,
  'getContactSubmissionsUser' : ActorMethod<[], Array<ContactSubmission>>,
  'getTestById' : ActorMethod<[bigint], Test>,
  'getTests' : ActorMethod<[], Array<Test>>,
  'getTopRankers' : ActorMethod<[], Array<Ranker>>,
  'login' : ActorMethod<[string, string], string>,
  'logout' : ActorMethod<[string], undefined>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
  'updateTest' : ActorMethod<
    [string, bigint, string, string, Array<Question>],
    undefined
  >,
  'validateSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];