/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CurrentAffairs {
  'id' : bigint,
  'content' : string,
  'date' : string,
}
export type ExamCategory = { 'ssc' : null } |
  { 'railway' : null } |
  { 'bpsc' : null } |
  { 'upsc' : null } |
  { 'banking' : null } |
  { 'stateExams' : null };
export interface Newspaper { 'id' : bigint, 'date' : string, 'link' : string }
export interface Question {
  'question' : string,
  'explanationHi' : [] | [string],
  'explanation' : [] | [string],
  'answer' : string,
  'optionsHi' : [] | [Array<string>],
  'questionHi' : [] | [string],
  'options' : Array<string>,
}
export interface Ranker {
  'studentName' : string,
  'rank' : bigint,
  'score' : bigint,
  'examCategory' : string,
}
export interface Slider {
  'id' : bigint,
  'title' : [] | [string],
  'imageUrl' : string,
}
export interface Student {
  'id' : bigint,
  'otp' : [] | [string],
  'password' : string,
  'mobileNumber' : string,
  'profilePhotoBase64' : [] | [string],
  'registeredAt' : Time,
}
export interface Test {
  'id' : bigint,
  'title' : string,
  'negativeMarkValue' : number,
  'category' : ExamCategory,
  'questions' : Array<Question>,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCurrentAffairs' : ActorMethod<[string, string, string], undefined>,
  'addNewspaper' : ActorMethod<[string, string, string], undefined>,
  'addRanker' : ActorMethod<[string, string, string, bigint], undefined>,
  'addSlider' : ActorMethod<[string, string, [] | [string]], undefined>,
  'addTest' : ActorMethod<
    [string, string, Array<Question>, bigint, number, ExamCategory],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCurrentAffairs' : ActorMethod<[string, bigint], undefined>,
  'deleteNewspaper' : ActorMethod<[string, bigint], undefined>,
  'deleteRanker' : ActorMethod<[string, bigint], undefined>,
  'deleteSlider' : ActorMethod<[string, bigint], undefined>,
  'deleteTest' : ActorMethod<[string, bigint], undefined>,
  'generateQuestions' : ActorMethod<[string, string, string], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentAffairs' : ActorMethod<[], Array<CurrentAffairs>>,
  'getNewspapers' : ActorMethod<[], Array<Newspaper>>,
  'getSliders' : ActorMethod<[], Array<Slider>>,
  'getStudentProfile' : ActorMethod<[string], [] | [Student]>,
  'getStudents' : ActorMethod<[string], Array<Student>>,
  'getTestById' : ActorMethod<[bigint], Test>,
  'getTests' : ActorMethod<[], Array<Test>>,
  'getTopRankers' : ActorMethod<[], Array<Ranker>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], string>,
  'logout' : ActorMethod<[string], undefined>,
  'registerStudent' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'studentLogin' : ActorMethod<[string, string], string>,
  'studentLogout' : ActorMethod<[string], undefined>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
  'updateStudentProfilePhoto' : ActorMethod<[string, string], undefined>,
  'updateTest' : ActorMethod<
    [string, bigint, string, Array<Question>, bigint, number, ExamCategory],
    undefined
  >,
  'validateSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];