/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'category' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const Ranker = IDL.Record({
  'studentName' : IDL.Text,
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'examCategory' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRanker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Question)],
      [],
      [],
    ),
  'deleteRanker' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'generateQuestions' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Question)], []),
  'getContactSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getContactSubmissionsUser' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getTestById' : IDL.Func([IDL.Nat], [Test], ['query']),
  'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getTopRankers' : IDL.Func([], [IDL.Vec(Ranker)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(Question)],
      [],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'category' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const Ranker = IDL.Record({
    'studentName' : IDL.Text,
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'examCategory' : IDL.Text,
  });
  
  return IDL.Service({
    'addRanker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Question)],
        [],
        [],
      ),
    'deleteRanker' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'generateQuestions' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Question)],
        [],
      ),
    'getContactSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getContactSubmissionsUser' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getTestById' : IDL.Func([IDL.Nat], [Test], ['query']),
    'getTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getTopRankers' : IDL.Func([], [IDL.Vec(Ranker)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(Question)],
        [],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };